### ISSUE TITLE
When running Lab 1 the error "BadGzipFile: Not a gzipped file (b'\n\n') is produced"

### ISSUE THREAD

**Issue by KyVinhMai** [full-stack-deep-learning/fsdl-text-recognizer-2022-labs#4]
I'm running into problem where the line

"((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding="latin-1")" of the 3rd cell.

Produces "BadGzipFile: Not a gzipped file (b'\n\n') is produced".
 
I noticed the link "https://github.com/pytorch/tutorials/raw/master/_static/" is also empty

**Comment by HTCho1** [comment]
I also met the same problem.

My solution is as below.

1. Download mnist.pklgz from https://github.com/mnielsen/neural-networks-and-deep-learning/blob/master/data/mnist.pkl.gz
2. Replace exist mnist.pkl.gz to downloaded mnist.pkl.gz from ../data/downloaded/vector-mnist/
3. Run the code on notebook. You have to annotate below (2nd cell).

if not (path / filename).exists():
    content = requests.get(url + filename).content
    (path / filename).open("wb").write(content)
